name: Bug report
description: File a bug report to help us improve the project.
title: "[Bug]: "
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us make BETTER-LBNL-OS better! Please share as much detail as you can.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: This happens when I...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproduction if possible.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. Observe '...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: Include OS, Python version, BETTER-LBNL-OS version, and any other relevant context.
      placeholder: |
        - OS:
        - Python version:
        - BETTER-LBNL-OS version:
        - Installation method:
  - type: textarea
    id: logs
    attributes:
      label: Logs or stack traces
      description: Paste any relevant logs, stack traces, or screenshots.
      render: shell
