name: Question
description: Ask a question or request support for using BETTER-LBNL-OS.
title: "[Question]: "
labels:
  - question
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Need help or clarification? Let us know how we can assist.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Share any background information, code snippets, or resources that will help us answer quickly.
      render: shell
