"""Enum definitions used across the OS library."""

from enum import Enum


class BuildingSpaceType(Enum):
    OFFICE = "Office"
    HOTEL = "Hotel"
    K12 = "K-12 School"
    MULTIFAMILY_HOUSING = "Multifamily Housing"
    WORSHIP_FACILITY = "Worship Facility"
    HOSPITAL = "Hospital (General Medical & Surgical)"
    MUSEUM = "Museum"
    BANK_BRANCH = "Bank Branch"
    COURTHOUSE = "Courthouse"
    DATA_CENTER = "Data Center"
    DISTRIBUTION_CENTER = "Distribution Center"
    FASTFOOD_RESTAURANT = "Fast Food Restaurant"
    FINANCIAL_OFFICE = "Financial Office"
    FIRE_STATION = "Fire Station"
    NON_REFRIGERATED_WAREHOUSE = "Non-Refrigerated Warehouse"
    POLICE_STATION = "Police Station"
    REFRIGERATED_WAREHOUSE = "Refrigerated Warehouse"
    RETAIL_STORE = "Retail Store"
    SELF_STORAGE_FACILITY = "Self-Storage Facility"
    SENIOR_CARE_COMMUNITY = "Senior Care Community"
    SUPERMARKET_GROCERY = "Supermarket/Grocery Store"
    RESTAURANT = "Restaurant"
    PUBLIC_LIBRARY = "Public Library"
    OTHER = "Other"


class BenchmarkCategory(Enum):
    OFFICE = "OFFICE"
    HOTEL = "HOTEL"
    K12 = "K12"
    MULTIFAMILY_HOUSING = "MULTIFAMILY_HOUSING"
    WORSHIP_FACILITY = "WORSHIP_FACILITY"
    HOSPITAL = "HOSPITAL"
    MUSEUM = "MUSEUM"
    BANK_BRANCH = "BANK_BRANCH"
    COURTHOUSE = "COURTHOUSE"
    DATA_CENTER = "DATA_CENTER"
    DISTRIBUTION_CENTER = "DISTRIBUTION_CENTER"
    FASTFOOD_RESTAURANT = "FASTFOOD_RESTAURANT"
    FINANCIAL_OFFICE = "FINANCIAL_OFFICE"
    FIRE_STATION = "FIRE_STATION"
    NON_REFRIGERATED_WAREHOUSE = "NON_REFRIGERATED_WAREHOUSE"
    POLICE_STATION = "POLICE_STATION"
    REFRIGERATED_WAREHOUSE = "REFRIGERATED_WAREHOUSE"
    RETAIL_STORE = "RETAIL_STORE"
    SELF_STORAGE_FACILITY = "SELF_STORAGE_FACILITY"
    SENIOR_CARE_COMMUNITY = "SENIOR_CARE_COMMUNITY"
    SUPERMARKET_GROCERY = "SUPERMARKET_GROCERY"
    RESTAURANT = "RESTAURANT"
    PUBLIC_LIBRARY = "PUBLIC_LIBRARY"
    OTHER = "OTHER"

